name: On Code Change

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Run linting
        shell: bash
        run: yarn lint
      - name: Run tests
        shell: bash
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: lint-tests
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Run Build
        shell: bash
        run: yarn build